#!/usr/bin/env python3
"""Regenerate supabase/functions/mb-zoom-app/page.ts from zoom-app/index.html + zoom-app/app.js.
The Edge Function serves these two files (Supabase's --use-api bundler ships the entrypoint's imports only, so the
page travels as string constants). Run after every edit of index.html / app.js; tests/zoomapp_test.ts fails when
page.ts is stale (PAGE_HASH mismatch)."""
import hashlib, json, os, sys
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
html = open(os.path.join(here, "index.html"), encoding="utf-8").read()
js = open(os.path.join(here, "app.js"), encoding="utf-8").read()
digest = hashlib.sha256((html + "\n---\n" + js).encode("utf-8")).hexdigest()
out = f"""// GENERATED by zoom-app/build-page.py from zoom-app/index.html + zoom-app/app.js — do not edit here.
// PAGE_HASH = sha256(index.html + "\\n---\\n" + app.js); tests/zoomapp_test.ts recomputes it from the sources.
export const PAGE_HASH = {json.dumps(digest)};
export const INDEX_HTML = {json.dumps(html)};
export const APP_JS = {json.dumps(js)};
"""
dst = os.path.join(root, "supabase", "functions", "mb-zoom-app", "page.ts")
os.makedirs(os.path.dirname(dst), exist_ok=True)
if "--check" in sys.argv:
    cur = open(dst, encoding="utf-8").read() if os.path.exists(dst) else ""
    sys.exit(0 if cur == out else 1)
open(dst, "w", encoding="utf-8").write(out)
print(f"{os.path.relpath(dst, root)} <- index.html + app.js (sha256 {digest[:12]}…)")
